In [1]:
# 동작유무가 중요한게 아님, 결과를 계선하는 방식으로 반복
print("파이썬")

파이썬

In [4]:
# 자료구조 ( 리스트, 딕셔너리, 튜플, 셋)
a = [1,2,3]
print(a, type(a))

[1, 2, 3] <class 'list'>

In [5]:
b = {"name": "가나다", "age":13}
print(b, type(b))

{'name': '가나다', 'age': 13} <class 'dict'>

In [7]:
c={1,2,3, 4}
print(c, type(c))

{1, 2, 3, 4} <class 'set'>

In [8]:
# 튜플 : 값을 변경 불가
d = (1, 2, 3)
print(d, type(d))

(1, 2, 3) <class 'tuple'>

In [9]:
! pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3

In [ ]:
import pymysql

connection = pymysql.connect(
    host = "127.0.0.1",
    port = 13306,
    user = "root",
    password = "1234",
    db="db1",
    cursorclass=pymysql.cursors.DictCursor
)

cursor = connection.cursosr();

In [25]:
sql = "SELECT b.* FROM board b"
cursor.execute(sql)

rows = cursor.fetchall()

In [17]:
import pandas as pd
df = pd.DataFrame(rows)
df

,no,title,content,writer,hit,create_at
0,1,제목,내용1,작성자,101,2026-04-27 10:30:49
1,2,변경1,변경2,변경3,103,2026-04-27 11:10:52
2,3,제목,내용3,작성자,101,2026-04-27 11:10:54
3,4,제목,내용4,작성자,101,2026-04-27 11:10:56
4,5,제목변경,내용변경,변경자2,114,2026-04-27 11:10:57
5,6,제목,내용6,작성자,101,2026-04-27 11:10:59
6,7,제목,내용7,작성자,101,2026-04-27 11:11:00
7,8,제목,내용8,작성자,101,2026-04-27 11:11:01
8,9,제목,내용9,작성자,101,2026-04-27 11:11:03
9,10,Welcome to our store!,We are happy to have you here. Browse our item...,Admin,150,2026-04-27 16:30:55
10,11,Summer Sale Announcement,Get up to 50% off on selected items this summer!,Manager,320,2026-04-27 16:30:55
11,12,Customer Feedback Wanted,Please let us know how we can improve your sho...,Support,45,2026-04-27 16:30:55
12,13,신규 가입 이벤트 안내,"지금 가입하시면 10,000원 쿠폰을 드립니다! 많은 참여 부탁드려요.",마케팅팀,1240,2026-04-27 16:30:55
13,14,배송 지연 공지,최근 기록적인 폭우로 인해 일부 지역의 배송이 1~2일 지연될 수 있습니다.,물류센터,890,2026-04-27 16:30:55
14,15,Q&A: 결제 수단 추가,네이버페이와 카카오페이 결제가 가능한가요?,김민준,115,2026-04-27 16:44:01
15,16,Review: iPhone 15 Pro,The camera is just incredible. Best smartphone...,TechGuru,560,2026-04-27 16:44:01
16,17,공지: 포인트 소멸 안내,2025년 적립된 포인트가 이번 달 말일에 소멸될 예정입니다.,시스템,4200,2026-04-27 16:44:01
17,18,Event: 포토 리뷰 콘테스트,리뷰를 남겨주시는 분들 중 추첨을 통해 아이패드를 드립니다!,마케팅팀,780,2026-04-27 16:44:01
18,19,FAQ: 환불 규정,단순 변심에 의한 환불은 수령 후 7일 이내에만 가능합니다.,CS팀,210,2026-04-27 16:44:01
19,20,제목foo,내용bar,글쓴이wat,1,2026-04-28 15:09:53

In [20]:
df.to_csv('./csv/board.csv')

In [26]:
sql = "SELECT c.* FROM customer c"
cursor.execute(sql)
rows = cursor.fetchall()
df = pd.DataFrame(rows)
df.to_csv("./csv/customer.csv")

---

In [30]:
import pandas as pd

df = pd.read_csv("./csv/customer.csv")

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     int64
 1   email       32 non-null     object
 2   phone       30 non-null     object
 3   password    30 non-null     object
 4   name        31 non-null     object
 5   create_at   32 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.6+ KB

In [34]:
import pandas as pd

customer_master = pd.read_csv("http://114.207.245.181:13000/csv/customer_master.csv")
customer_master.to_csv("./csv/customer_master.csv")

In [35]:
customer_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   object
 1   customer_name      5000 non-null   object
 2   registration_date  5000 non-null   object
 3   email              5000 non-null   object
 4   gender             5000 non-null   object
 5   age                5000 non-null   int64
 6   birth              5000 non-null   object
 7   pref               5000 non-null   object
dtypes: int64(1), object(7)
memory usage: 312.6+ KB

In [36]:
customer_master.columns

Index(['customer_id', 'customer_name', 'registration_date', 'email', 'gender',
       'age', 'birth', 'pref'],
      dtype='object')

In [45]:
# 딕셔너리 타입으로 앞쪽에 원래:변경
t1 = {
    'customer_id': '고객아이디',
    'customer_name': '고객명',
    'registration_date': '등록일시',
    'email': '이메일',
    'gender': '성별',
    'age': '나이',
    'birth': '생년월일',
    'pref': '지역',
}

# inplace 옵션이 기본 False 이기때문에 생략하면 바뀌지 않는다
# customer_master = customer_master.rename(columns=t1, inplace=False)
customer_master = customer_master.rename(columns=t1)
customer_master

,고객아이디,고객명,등록일시,이메일,성별,나이,생년월일,지역
0,IK152942,김서준,2019-01-01 0:25,hirata_yuujirou@example.com,M,29,1990-06-10,대전광역시
1,TS808488,김예준,2019-01-01 1:13,tamura_shiori@example.com,F,33,1986-05-20,인천광역시
2,AS834628,김도윤,2019-01-01 2:00,hisano_yuki@example.com,F,63,1956-01-02,광주광역시
3,AS345469,김시우,2019-01-01 4:48,tsuruoka_kaoru@example.com,M,74,1945-03-25,인천광역시
4,GD892565,김주원,2019-01-01 4:54,oouchi_takashi@example.com,M,54,1965-08-05,울산광역시
...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52,hirayama_risa@example.com,F,77,1941-10-17,대전광역시
4996,HD758694,정영훈,2019-07-31 19:09,nakahara_mahiru@example.com,F,27,1991-11-13,광주광역시
4997,PL538517,정준기,2019-07-31 19:30,tabata_yuu1@example.com,F,73,1945-12-28,대전광역시
4998,OA955088,정도형,2019-07-31 22:32,setouchi_hikaru@example.com,F,75,1944-04-09,부산광역시
4999,HI349563,정지석,2019-07-31 22:49,horii_kanji@example.com,M,21,1998-02-06,서울특별시

In [54]:
customer_master.dtypes

고객아이디            object
고객명              object
등록일시     datetime64[ns]
이메일              object
성별               object
나이                int64
생년월일     datetime64[ns]
지역               object
dtype: object

In [53]:
# 현재 등록일시의 타입이 문자인데 날짜 타입으로 변환하기
customer_master['등록일시'] = pd.to_datetime(customer_master['등록일시'], format='%Y-%m-%d %H:%M')
customer_master['생년월일'] = pd.to_datetime(customer_master['생년월일'], format='%Y-%m-%d')

In [63]:
customer_master['년'] = customer_master['생년월일'].dt.year
customer_master['월'] = customer_master['생년월일'].dt.month
customer_master['일'] = customer_master['생년월일'].dt.day

In [ ]:
# 나이 다시 계산하기 한국식 나이이므로 +1
customer_master['나이'] = 2026 - customer_master['년'] + 1
customer_master

In [ ]:
bins = [0, 9, 19, 29, 39, 49, 59, 69, 79, 150]
labels = []
labels = ["0대", "10대", "20대", "30대", "40대", "50대", "60대", "70대", "80이상",]
customer_master['연령대'] = pd.cut(customer_master['나이'], bins=bins, labels=labels, right=True)
customer_master

In [ ]:
customer_master.to_pickle('./pkl/customer_master.pkl')

---

In [ ]:
import pandas as pd
df = pd.read_pickle('./pkl/customer_master.pkl')
df

In [83]:
# 물품 정보 읽기

item_master = pd.read_csv('http://114.207.245.181:13000/csv/item_master.csv')
print(item_master)
print(item_master.columns)

  item_id item_name  item_price
0    S001      PC-A       50000
1    S002      PC-B       85000
2    S003      PC-C      120000
3    S004      PC-D      180000
4    S005      PC-E      210000
Index(['item_id', 'item_name', 'item_price'], dtype='object')

In [99]:
item_master.to_pickle('./pkl/item_master.pkl')

In [88]:
t2 = {
    'item_id': '물품코드', 
    'item_name': '물품명', 
    'item_price': '물품가격',
}
item_master = item_master.rename(columns=t2)
print(item_master.dtypes)
item_master

물품코드    object
물품명     object
물품가격     int64
dtype: object

   물품코드   물품명    물품가격
0  S001  PC-A   50000
1  S002  PC-B   85000
2  S003  PC-C  120000
3  S004  PC-D  180000
4  S005  PC-E  210000

In [92]:
host = 'http://114.207.245.181:13000'
transaction_1 = pd.read_csv(f'{host}/csv/transaction_1.csv')
transaction_1.head(3)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502
1    T0000000114   50000  2019-02-01 01:37:23    HD678019
2    T0000000115  120000  2019-02-01 02:34:19    HD298120

In [93]:
transaction_2 = pd.read_csv(f'{host}/csv/transaction_2.csv')
transaction_2.head(3)

  transaction_id   price         payment_date customer_id
0    T0000005113  295000  2019-06-15 07:20:27    TS169261
1    T0000005114   50000  2019-06-15 07:35:47    HI599892
2    T0000005115   85000  2019-06-15 07:56:36    HI421757

In [119]:
# transaction_1에 transaction_2를 붙이기

transaction = pd.concat([transaction_1, transaction_2], ignore_index=True)
print(transaction.columns)
transaction

Index(['transaction_id', 'price', 'payment_date', 'customer_id'], dtype='object')

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [127]:
t3 = dict(zip(
    ['transaction_id', 'price', 'payment_date', 'customer_id'], 
    ['거래코드', '결제금액', '결제일시', '고객아이디',]
))
transaction = transaction.rename(columns = t3)
transaction['결제일시'] = pd.to_datetime(transaction['결제일시'], format='%Y-%m-%d %H:%M:%S')
print(transaction.dtypes)
transaction.to_pickle('./pkl/transaction_master.pkl')
transaction

거래코드             object
결제금액              int64
결제일시     datetime64[ns]
고객아이디            object
dtype: object

             거래코드    결제금액                결제일시     고객아이디
0     T0000000113  210000 2019-02-01 01:36:57  PL563502
1     T0000000114   50000 2019-02-01 01:37:23  HD678019
2     T0000000115  120000 2019-02-01 02:34:19  HD298120
3     T0000000116  210000 2019-02-01 02:47:23  IK452215
4     T0000000117  170000 2019-02-01 04:33:46  PL542865
...           ...     ...                 ...       ...
6781  T0000006894  180000 2019-07-31 21:20:44  HI400734
6782  T0000006895   85000 2019-07-31 21:52:48  AS339451
6783  T0000006896  100000 2019-07-31 23:35:25  OA027325
6784  T0000006897   85000 2019-07-31 23:39:35  TS624738
6785  T0000006898   85000 2019-07-31 23:41:38  AS834214

[6786 rows x 4 columns]

%store transaction

In [131]:
import shelve

with shelve.open('conda_store') as db:
    db['transaction'] = transaction